#!/bin/sh -e

case $(uname -s) in
  Darwin) scons -Q --jobs $(sysctl -n hw.ncpu) os=emscripten arch=wasm ;;
  Linux) scons -Q --jobs $(nproc) os=emscripten arch=wasm ;;
  *) echo Unknown OS $(uname -s)
esac
