#!/bin/sh -ex

cd primordialsoup
./build os=emscripten arch=wasm
cd ..

# All this moving sources around is to make build-time relative paths the same
# as our desired load-time relative paths. Eventually this should be handled by
# WebCompiler when we have I/O libraries.
mkdir -p out
cp primordialsoup/out/ReleaseEmscriptenWASM/primordialsoup.* out
cp primordialsoup/out/snapshots/*.vfuel out
cp primordialsoup/newspeak/*.ns out
mkdir -p out/CodeMirror/lib
mkdir -p out/CodeMirror/addon/display
cp CodeMirror/lib/codemirror.js out/CodeMirror/lib/codemirror.js
cp CodeMirror/lib/codemirror.css out/CodeMirror/lib/codemirror_css.css
cp CodeMirror/addon/display/autorefresh.js out/CodeMirror/addon/display/autorefresh.js
cp src/* out

cd out
../primordialsoup/out/ReleaseHost/primordialsoup \
    ../primordialsoup/out/snapshots/CompilerApp.vfuel \
    *.ns \
    RuntimeWithMirrors WebCompiler WebCompiler.vfuel
../primordialsoup/out/ReleaseHost/primordialsoup \
    WebCompiler.vfuel \
    *.ns \
    *.webp \
    CodeMirror/lib/codemirror.js \
    CodeMirror/lib/codemirror_css.css \
    CodeMirror/addon/display/autorefresh.js \
    RuntimeWithMirrors HopscotchIDE HopscotchIDE.vfuel \
    Runtime Particles Particles.vfuel \
    RuntimeWithMirrors TestRunner TestRunner.vfuel \
    Runtime BenchmarkRunner BenchmarkRunner.vfuel
cd ..
