#!/bin/sh -ex
case $(uname -s) in
  Linux) BROWSER=--browser=firefox ;;
esac
emrun --serve_root=out $BROWSER "ReleaseEmscriptenWASM/primordialsoup-emrun.html?snapshot=../snapshots/HopscotchTestRunner.vfuel"
