#!/bin/sh -ex
out/ReleaseHost/primordialsoup out/snapshots/HostTestRunner.vfuel
case $(uname -s) in
  Linux) BROWSER=--browser=firefox ;;
esac
emrun --serve_root=out $BROWSER "ReleaseEmscriptenWASM/primordialsoup-emrun.html?snapshot=../snapshots/WebTestRunner.vfuel"
